### ISSUE TITLE
Mercie bien for this!

### ISSUE THREAD

**Issue by axgkl** [pawamoy/copier-poetry#2]
Just feel the urge to express my gratitude for this, Timothée.

I admit, I'm more the freestyler guy, who first has to break everything before he finally adopts best practices - plus the problem of (no possibility to) updating always turned me off project templates. But this beauty is really so well executed, I had zero problems to understand it within a few hours and I did not even know copier before. Yeah in fact that was half of the understanding time, finding that copier takes the last *tagged* version, when its a repo, that drove me nuts, totally not your fault  :-)
 
Regarding this, It's so cool that I finally found something, which does not restrict me at all, freedom wise, but still gives me a ton of python goodies w/o investing any work - including your mkdocstrings plugin, which also rocks.
 
I really think this deserves more attention, I would suggest giving a talk at pycon or so. 

Anyway, sorry for the noise - just wanted to say thanks. You saved me minimum a week or so, investigating tools and putting it all together until finding I picked the wrong tools (e.g. pipenv) and so.. if I consider my would be result with this, I tend to think its a month :-)

PS2:
If you want a real reason for a ticket: I think the licenses with quotes break in the post_generation.py script, some escaping required I guess:

```bash
  > Running task 1 of 1: python scripts/post_generation.py
  File "scripts/post_generation.py", line 30
    "BSD 2-Clause "Simplified" License"
                            ^
SyntaxError: invalid syntax
```

Interrupting copier and running the postgen script in foreground, I see that it has been rendered into this:

```python
def copy_license():
    """Copy the selected rendered license to the LICENSE file."""
    target = "LICENSE"
    if not os.path.exists("LICENSE"):
        source = os.path.join(
            "licenses",
            "BSD 2-Clause "Simplified" License"
                .replace('"', "")

```
=> seems you either delete the apos in the license names or use a filter here:

```python
def copy_license():
    """Copy the selected rendered license to the LICENSE file."""
    target = "LICENSE"
    if not os.path.exists("LICENSE"):
        source = os.path.join(
            "licenses",
            "[[ copyright_license ]]"     <--------------- here
                .replace('"', "")
                .replace("'", "")
                .replace("/", "-")
                .replace(" ", "_")
                .replace("*", "_"))
        shutil.copyfile(source, target)
```
Thanks again,
Cheers,
Gunther

**Comment by pawamoy** [comment]
My girlfriend and I agree on this: this is the BEST COMMENT I EVER RECEIVED on one of my projects, so thank you a thousand times, we're actually celebrating, she organized a small surprise for me after I shared this with her :rofl:

Cheers to you!!!

I will take the time to answer properly tomorrow :relaxed:

But really, wow, thank you, this is heart warming, and I'll take extra care to improve this template documentation which does not always follow the changes I push (you should probably fork it because it evolves quickly).

Anyway, talk tomorrow :sparkles:

**Comment by axgkl** [comment]
...while my wife asked my why I'm smiling so much, since very recently ;-)
Can't believe, looking at what you did otherwise up to now, that a simple thanks has such impact - you must be really young and so I'm pretty sure, given your productivity, that you'll be playing in the same league as Chad Smith, Dag Brattli (RxPy), Hynek Schlawack (structlog, attrs) or Armin (to list my heroes) and can pick the company you'll want to work for ;-)   

Honestly I was really getting crazy, trying to finish the famous last mile and publish the  stuff I did in my ivory tower for the last year or so (I mean internally in my company, where a lot of sharks..., I mean IT/python cracks hang around, which would immediately reject it when its not top notch developer experience).
Now it *will* be top notch.
In fact, I already pushed a first version and all just worked fine, after all adaptions (okee, that flakehell baseline file I really needed, that was really depressing, I'm so terrible ;-) ).
Oh yes, and while adapting it, I found that this is not only a project template, but its an extremely good tutorial as well: You learn in the most convenient and fast manner cool yaml features, flake8 parametrization, pytest fixtures and parallelisation, best coverage setup, how to properly do cli, even some make mechanics[1] I always ignored.
And and and...
Enough said, have to now add a 'publish_org' duty to the template (tried hard to keep emacs out of my vim driven IT life, but with their insane literate programming  features they finally got me into the church). 
And you should not care about that "pseudo ticket" but rather enjoy your time with your gf (glad you found one which understands the 'urge-to-create/crazy artist' gene in you) - no black metal day today (that was funny to read btw. I turned f**ng fifty this year and I'm really glad the "young guns" can still appreciate the good music of my own 20ies and 30ies  ;-)

> improve this template documentation 

Its really really nice that this does not make me sweat, because of copier's update feature. My fork went immediately on to our internal company server (including *proper* credits to you, in my case next to IBMs' Node-RED and ReactiveX Python, yes that important: Because this last mile from "working stuff" to real product is actually half of the whole way and you reduced that down to a minimum. 

Cheers,
Gunther

[1]:  allthough I still could not figure how to pass the version  parameter into the release duty, solved via `def release(ctx, version=os.environ.get('VERSION')):` for now and say `make release VERSION=...`

**Comment by pawamoy** [comment]
Not so young, I'm 29 :smile: ! I couldn't ask more than to play one day in the same league as those you mentioned :slightly_smiling_face: 

I do care about this ticket, you raised an issue that needs to be fixed. I think I'll put all the licenses text into one big LICENSE file with Jinja conditions to render only the selected one. No more post-processing.

And yes, I'm very thankful for being with my amazing girlfriend! She'll be my wife one day!

I don't know what are IBMs' Node-RED and ReactiveX Python, I'll check them out. Thank you so much for the credits!!

It's funny you mention that "passing args to duty through the Makefile" issue, because it was absolutely bothering me as well, so I made it possible! The short version is:

```Makefile
args = $(foreach a,$($(subst -,_,$1)_args),$(if $(value $a),$a=$($a)))

release_args = version
docs_serve_args = host port
# etc.

.PHONY: $(BASIC_DUTIES)
$(BASIC_DUTIES):
	@$(DUTY) $@ $(call args,$@)

.PHONY: $(QUALITY_DUTIES)
$(QUALITY_DUTIES):
	@bash scripts/multirun.sh duty $@ $(call args,$@)
```

It's a bit of dark magic, I'll write a small blog post soon to explain it better! As long are arguments are unique across duties, they are correctly dispatched to their respective duties, whatever the order they are typed on the command line!

```bash
make test match="this and that" changelog release version=0.15.1  # right order
make test changelog match="this and that" version=0.15.1 release  # different args order, but equivalent!
```

**Comment by pawamoy** [comment]
Oh my, I forgot: I can't thank you enough for the sponsoring Gunther! You are *spoiling* me! I'll put that fuel to good use :smile:

**Comment by axgkl** [comment]
> args = $(foreach a,$($(subst -,_,$1)_args),$(if $(value $a),$a=$($a)))

thats really a funny one...  I could do that stuff in bash but `make` I always manage to avoid - I love python for a reason :-) But yeah, it looks more declarative (exclusive such hacks) but I'm not sure if it actually is :-)
Anyway I think I'm happy with my `publish version=...`  and the `os.environ.get()` in the duty func sig., don't even need to declare the args and its not exported, so I don't see a risk spamming into the actual subprocess spawned. 

ReactiveX  (and its python variant RxPY) you should really check out, that's something for life. But prepare quite some time - netflix once measured that the joe average  usually needs  a month to get his head around it :-)
I use it for nearly everything, also sync stuff but where it really shine is async stuff and when your run in to syncronization problems or system overload situations (where e.g. python's `async` will [kill](https://lucumr.pocoo.org/2020/1/1/async-pressure/) you.
Check e.g. this https://rxviz.com/examples/higher-order-observable  and play with the code and think about *how* they can do that visualizer... then you'll begin to understand that the left side is not lala land imperative code but a declaration. I.e. something which is understandable by the machine before but also while[1] any data flows - and still you can build arbitrary complex systems with that....  Does not matter that its javascript, you write the same pipeline in python, the operators are standardized...
 
[1] This means for example that the producer knows if somebody is listening on the other side of the pipeline - and can stop producing when nobody does... or produce throttled when the system is in a burst situation, whatever has to do with time you have under complete control.

Regarding the sponsoring - you are killing me... Here in Munich we can't find any single Software engineer anymore and I'm not talking about *your* quality... Isn't this the same in France?

**Comment by pawamoy** [comment]
Hey Gunther!

I can't tell for France in general, but in my short experience it feels like we get a constant (though maybe not sufficient) refill of software engineers from universities and other schools here, in the east of France. Well, I never had to *recruit* software engineers so I might be totally wrong and companies struggle to find enough (and good enough)!

I checked RxPy, it does look very interesting! I totally see the advantage of being able to visualize and grasp the flow of data in a few lines of code (instead of many loops and other constructs). Maybe I'll try to play with it for my `mvodb` project :slightly_smiling_face:

**Comment by pawamoy** [comment]
Hey @AXGKl, just in case you didn't already see it, I've deployed some documentation on GitHub pages: https://pawamoy.github.io/copier-poetry/. Hope it helps even further!

**Comment by pawamoy** [comment]
Hey again @AXGKl!

I've created a little brother for this template: https://github.com/pawamoy/copier-pdm!
It uses PDM instead of Poetry for project management.
PDM has several advantages over Poetry (some of which could be interesting in corporate environments): it reads pip's config for index URL and other settings, it doesn't use virtualenvs but rather PEP582 and a `__pypackages__` directory, and it has groups for dev-dependencies! @frostming has been working hard on it, and it's already a joy to use :slightly_smiling_face:

There's also a Copier + PDM template directly provided by the pdm-project: https://github.com/pdm-project/copier-pdm, and it deserves to be looked at :+1: 

That's it, have a nice day!

**Comment by axgkl** [comment]
Hey, sorry for the delay, I'm alive. Loaded like hell - but still alive;-)
And: wow. I must say, I concluded last year 582 is not there yet but I did not invest much research.  Just saw that tool, "written in Rust(tm)" - pyflow.
 
=> I'll check pdm out, using your template, once I get back a hold of my tasklist...
