### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by znd4** [pawamoy/copier-poetry#5]
Sorry if I missed an existing option.

I feel like a bad person asking for this, but would you be up for a PR that adds an option to not include a License for internal projects? I'm guessing I can delete the license file + license line in pyproject.toml, but I'm worried about that upsetting copier (this is my first time picking up copier)

**Comment by pawamoy** [comment]
Don't worry haha, I totally understand :smile: Lots of companies do not have the need for licenses since their projects stay "in-house". I don't think it's a problem for Copier if you simply delete the file and line, but I do think that, after generating the project the first time, you should add the LICENSE file to git, commit it, *and then delete it*. Same for the license line in pyproject.toml. If you never track it with git, upon updates Copier will regenerate it I think, whereas if Copier can see that you "git removed" it, it won't regenerate it each time you `copier update`. Does it make sense to you? @Yajo (sorry to bring you in) could you confirm this behavior?

**Comment by yajo** [comment]
Yes, that's how it should work.

And Copier won't sue you. 🤣

**Comment by pawamoy** [comment]
Closing, feel free to continue the discussion though :slightly_smiling_face:
